# Generated by Django 5.2.4 on 2025-07-12 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Business', 'Business'), ('Culture', 'Culture'), ('World', 'World'), ('Sports', 'Sports'), ('Health', 'Health'), ('Uzbekistan', 'Uzbekistan')], max_length=50)),
                ('image_url', models.URLField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_lead', models.BooleanField(default=False, help_text='Check this for the main lead story.')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
