# Generated by Django 5.2.4 on 2025-07-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Texnologiya', 'Texnologiya'), ('Biznes', 'Biznes'), ('Madaniyat', 'Madaniyat'), ('Dunyo', 'Dunyo'), ('Sport', 'Sport'), ('Salomatlik', 'Salomatlik'), ('O`zbekiston', 'O`zbekiston')], max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_lead',
            field=models.BooleanField(default=False, help_text='Asosiy yangilik sifatida belgilash uchun tanlang.'),
        ),
    ]
