# Generated by Django 5.2.4 on 2025-07-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_category_alter_article_is_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default=1, help_text='Qidiruv natijalari uchun qisqacha tavsif (160 belgidan oshmasin).', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('O`zbekiston', 'O`zbekiston'), ('Jahon', 'Jahon'), ('Iqtisodiyot', 'Iqtisodiyot'), ('Jamiyat', 'Jamiyat'), ('Fan-texnika', 'Fan-texnika'), ('Sport', 'Sport')], max_length=50),
        ),
    ]
